---
- name: Ensure gcp storage container exists
  command: gcp storage container create --name {{ artifacts_container }}

- name: Upload to gcp storage
  command: gcp storage  upload -c {{ artifacts_container }} --name {{ artifact }} -f {{ artifact_path }}
  async: 3600
  poll: 10
