---
- hosts: localhost
  become: yes
  vars_files:
    - "{{inventory_dir}}/secrets.yml"
  tasks:
    - name: upload to gcloud storage
      include_role:
        name: gcp-cloud-storage
        tasks_from: upload.yml
      vars:
        gcp_bucket_name: "{{ gcloud_artifact_bucket_name }}"
        dest_folder_name: "{{ artifacts_container }}"
        dest_file_name: "{{ artifact }}"
        local_file_or_folder_path: "{{ artifact_path }}"
      when: cloud_service_provider == "gcloud"
